config/routes.rb
BasicAuth::Application.routes.draw do

  root :to=>"home#index"

  get "sign_in" => "authentication#sign_in"
  get 'signed_out' => "authentication#signed_out"
  get 'change_password' => "authentication#change_password"
  get 'forgot_password' => "authentication#forgot_password"
  get "new_user" => "authentication#new_user"
  get "password_sent" => "authentication#password_sent"
  get "user_posts" => "posts#user_posts"

  get "account_settings" => "authentication#account_settings"

  post "sign_in" => "authentication#login"
  put "new_user" => "authentication#register"
  put "account_settings" => "authentication#set_account_info"

  get "static_pages/sent"
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :name, :brand, :phone, :model, :problem, :result, :id, :username, :user_id
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  attr_accessible :email, :username, :password, :password_confirmation, :new_password, :new_password_confirmation, :remember_me
  attr_accessor :password, :new_password, :previous_email, :previous_username, :remember_me
  before_save :encrypt_password

  validates_confirmation_of :password

  validates_confirmation_of :new_password, :if => Proc.new {|user|
    !user.new_password.nil? && !user.new_password.empty? }

  validates_presence_of :password, :on => :create

  validates_presence_of :email, :if => Proc.new {|user|
    user.previous_email.nil? || user.email != user.previous_email}

  validates_presence_of :username, :if => Proc.new {|user|
    user.previous_username.nil? || user.username != user.previous_username}

  validates_uniqueness_of :email, :if => Proc.new {|user|
    user.previous_email.nil? || user.email != user.previous_email}

  validates_uniqueness_of :username, :if => Proc.new {|user|
    user.previous_username.nil? || user.username != user.previous_username}

  def initialize(attributes = {})
    super     # must allow the active record to initialize!
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def update(attributes = {})
    super     # must allow the active record to initialize!
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def self.authenticate_by_email(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.authenticate_by_username(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def current_user
    # Note: we want to use "find_by_id" because it's OK to return a nil.
    # If we were to use User.find, it would throw an exception if the user can't be found.
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    if current_user.nil?
      flash[:error] = 'Bu sayfaya giris yapmak icin uye olmalisiniz.'
      redirect_to :root
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  before_filter :authenticate_user, :only => [:account_settings, :set_account_info]

  def sign_in
    @user = User.new
  end

  def signed_out
    session[:user_id] = nil
    flash[:notice] = "Cikis yaptiniz"
    redirect_to :root
  end

  def new_user
    @user = User.new
  end

  def account_settings
    @user = current_user
  end

  def set_account_info
    old_user = current_user

    # verify the current password by creating a new user record.
    @user = User.authenticate_by_username(old_user.username, params[:user][:password])

    # verify
    if @user.nil?
      @user = current_user
      @user.errors[:password] = "Girdiginiz sifre yanlis."
      render :action => "account_settings"
    else
      # update the user with any new username and email
      @user.update(params[:user])
      # Set the old email and username, which is validated only if it has changed.
      @user.previous_email = old_user.email
      @user.previous_username = old_user.username

      if @user.valid?
        # If there is a new_password value, then we need to update the password.
        @user.password = @user.new_password unless @user.new_password.nil? || @user.new_password.empty?
        @user.save
        flash[:notice] = 'Hesap ayarlariniz degistirildi.'
        redirect_to :root
      else
        render :action => "account_settings"
      end
    end
  end

  def register
    @user = User.new(params[:user])

    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome.'
      redirect_to :root
    else
      render :action => "new_user"
    end
  end

  def login
    username_or_email = params[:user][:username]
    password = params[:user][:password]

    if username_or_email.rindex('@')
      email=username_or_email
      user = User.authenticate_by_email(email, password)
    else
      username=username_or_email
      user = User.authenticate_by_username(username, password)
    end

    if user
      session[:user_id] = user.id
      flash[:notice] = 'Hosgeldin ' + user.username.to_s + "."
      redirect_to :root
    else
      @user = User.new
      flash.now[:error] = 'Girdiginiz kullanici adi ve ya sifre yanlis.'
      render :action => "sign_in"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "pass", except: [:create, :new, :user_posts]
  before_filter :authenticate_user, :only => [:new, :create,:user_posts ]

  def new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:name, :brand, :model, :problem, :result))
      redirect_to @post
    else
      render 'edit'
    end

  end
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create

    @user = @current_user
    #@post = Post.new(post_params)
    @post = @user.posts.create(params[:post].permit(:name, :brand, :phone, :model, :problem, :user_id))
    #@post.save
    redirect_to static_pages_sent_path
  end

  def user_posts
    @posts = Post.where("user_id = ?", current_user.id)
  end

  private
  def post_params
    params.require(:post).permit(:name, :brand, :phone, :model, :problem, :result, :user_id, :username)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def sent
  end

  def user_posts

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_field_error(model, field)
    s=""

    if !model.errors[field].empty?
      s =
          <<-EOHTML
           <div id="error_message">
             #{model.errors[field][0]}
           </div>
      EOHTML
    end

    s.html_safe
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authentication/account_settings.html.erb
<p>Hesap ayarları</p>
<%= form_for @user, :as => :user, :url => account_settings_path, :method => :put do |f| %>
    <p>
      <%= f.label 'Şu anki şifre:' %><br/>
      <%= f.password_field :password %>
      <%= show_field_error(@user, :password) %>
    </p>
    <p>
      <%= f.label 'Kullanıc adı: (Kullanıcı adınızı değiştirmeyecekseniz burayı değiştirmeyin)' %><br/>
      <%= f.text_field :username %>
      <%= show_field_error(@user, :username) %>
    </p>
    <p>
      <%= f.label 'E-mail: (E-mailinizi değiştirmeyecekseniz burayı değiştirmeyin)' %><br/>
      <%= f.text_field :email %>
      <%= show_field_error(@user, :email) %>
    </p>
    <p>
      <%= f.label 'Yeni şifre: (Şifrenizi değiştirmeyecekseniz boş bırakınız)' %><br/>
      <%= f.password_field :new_password %>
      <%= show_field_error(@user, :new_password) %>
    </p>
    <p>
      <%= f.label 'Şifre doğrulama:' %><br/>
      <%= f.password_field :new_password_confirmation %>
      <%= show_field_error(@user, :new_password_confirmation) %>
    </p>
    <p>
      <%= f.submit 'Güncelle' %>
    </p>
    <%= link_to 'Anasayfa', :root %><br>
<% end %>

app/views/authentication/new_user.html.erb
<h1>Üye Olmak için aşağıdaki formları doldurunuz</h1>

<p>Üye ol</p>
<%= form_for @user, :as => :user, :url => new_user_path, :method => :put do |f| %>
    <p>
      <%= f.label 'Kullanıcı adı:' %><br/>
      <%= f.text_field :username %>
      <%= show_field_error(@user, :username) %>
    </p>
    <p>
      <%= f.label 'E-mail:' %><br/>
      <%= f.text_field :email %>
      <%= show_field_error(@user, :email) %>
    </p>
    <p>
      <%= f.label 'Şifre:' %><br/>
      <%= f.password_field :password %>
      <%= show_field_error(@user, :password) %>
    </p>
    <p>
      <%= f.label 'Şifre doğrulama:' %><br/>
      <%= f.password_field :password_confirmation %>
      <%= show_field_error(@user, :password_confirmation) %>
    </p>
    <p>
      <%= f.submit 'Üye ol' %>&nbsp;&nbsp;&nbsp;
      <%= f.submit 'Formu temizle', :type => 'reset' %>
    </p>
    <%= link_to 'Anasayfa', :root %><br>
<% end %>

app/views/authentication/sign_in.html.erb
<h1>Giriş yapabilmek için aşağıdaki formları doldurunuz</h1>
<p>Giriş yap</p>
<%= form_for @user, :as => :user, :url => sign_in_path(@user) do |f| %>
    <p>
      <%= f.label 'Kullanıcı adı ya da e-mail:' %><br />
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label 'Şifre:' %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.submit 'Giriş yap' %>&nbsp;&nbsp;&nbsp;
      <%= f.submit 'Formu temizle', :type => 'reset' %>
    </p>
    <%= link_to 'Anasayfa', :root %><br>
<% end %>

app/views/authentication/user_posts.html.erb
<% @posts.each do |post| %>
    <tr>
      <td><%= post.name %></td>
      <td><%= post.brand %></td>
      <td><%= post.model %></td>
      <td><%= post.problem %></td>
      <td><%= post.result %></td>
      <td><%= link_to 'Göster', post %></td>
      <td><%= link_to 'Değiştir', edit_post_path(post) %></td>
      <td><%= link_to 'Sil', post_path(post),
                      method: :delete, data: { confirm: 'Emin misiniz?' } %></td>
    </tr>
<% end %>

app/views/home/index.html.erb
<h1>Notebook Tedavi Merkezine Hoşgeldiniz</h1>
<%= link_to "Cihaz listesi(Admin)", controller: "posts" %><br>   </br>
<%= link_to 'Arıza bildirimi(Müşteri)', new_post_path %><br>     </br>
<%= link_to 'Daha önceki bildirdiğim arızalar(Müşteri)', user_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicAuth</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


  <% if current_user %>
      <br>
    <div margin-left="20px"><%= current_user.username %> olarak giriş yaptınız. </div>
    <div>
      <%= link_to "Çıkış Yap", signed_out_path %>
      <%= link_to "Hesap Ayarları", account_settings_path %>
  <% else %>
      <%= link_to "Üye Ol", new_user_path %> or
      <%= link_to "GirisYap", sign_in_path %>
    </div>
  <% end %>


<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <p>
    <%= f.label :Marka %><br>
    <%= f.text_field :brand %>
  </p>

  <p>
    <%= f.label :Model %><br>
    <%= f.text_field :model %>
  </p>

  <p>
    <%= f.label :problem %><br>
    <%= f.text_area :problem %>
  </p>

  <p>
    <%= f.label :Sonuç %><br>
    <%= f.text_area :result %>
  </p>
 
  <p>
    <%= f.submit "Değiştir" %>
  </p>
<% end %>

app/views/posts/after.html.erb
<h1>Arızanız bildirilmiştir. En kısa zamanda cihazınızı tamir merkezimize getiriniz</h1>

app/views/posts/edit.html.erb
<h1>Girdiyi değiştir</h1>

<%= render 'form' %>

<%= link_to 'Anasayfa', :root %><br>
<%= link_to "Cihaz listesine dön", controller: "posts" %>

app/views/posts/index.html.erb
<h1>Müşteri Cihaz Listesi</h1>
 
<table border="3">
  <tr>
    <th>İsim - Soyisim</th>
    <th>Marka</th>
    <th>Model</th>
    <th>Sorun</th>
    <th>Durum</th>
  </tr>
 
  <% @posts.each do |post|  %>
    <tr>
      <td><%= post.name %></td>
      <td><%= post.brand %></td>
      <td><%= post.model %></td>
      <td><%= post.problem %></td>
      <td><%= post.result %></td>
      <td><%= link_to 'Göster', post %></td>
      <td><%= link_to 'Değiştir', edit_post_path(post) %></td>	
      <td><%= link_to 'Sil', post_path(post),
                    method: :delete, data: { confirm: 'Emin misiniz?' } %></td>
    </tr>
  <% end %>
</table>
 <br><br><br><br>
<%= link_to 'Anasayfa', :root %>

app/views/posts/new.html.erb
<h1>Arıza bildirim formu</h1>
<%= form_for :post, url: posts_path do |f| %>
    <p>
    <p>İsim - Soyisim</p>
    <%= f.text_field :name %>
    </p>

    <p>
    <p>Tel No</p>
    <%= f.text_field :phone %>
    </p>

    <p>
    <p>Marka</p>
    <%= f.text_field :brand %>
    </p>

    <p>
      <%= f.label :model %><br>
      <%= f.text_field :model %>
    </p>

    <p>
      <%= f.label :problem %><br>
      <%= f.text_area :problem %>
    </p>

    <p>
      <%= f.submit "Gönder" %>
    </p>
<% end %>

<%= link_to 'Anasayfa', :root %>

app/views/posts/show.html.erb
<p>
  <strong>İsim Soyisim:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Telefon:</strong>
  <%= @post.phone %>
</p>

<p>
  <strong>Marka:</strong>
  <%= @post.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @post.model %>
</p>

<p>
  <strong>Durum:</strong>
  <%= @post.result %>
</p>

<%= link_to 'Bu girdiyi değiştir', edit_post_path(@post) %><br>
<%= link_to "Cihaz listesine dön", controller: "posts" %><br>	
<%= link_to 'Anasayfa', :root %>

app/views/posts/user_posts.html.erb
<h1>Müşteri Cihaz Listesi</h1>

<table border="3">
  <tr>
    <th>İsim - Soyisim</th>
    <th>Marka</th>
    <th>Model</th>
    <th>Sorun</th>
    <th>Durum</th>
  </tr>

  <% @posts.each do |post|  %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.brand %></td>
        <td><%= post.model %></td>
        <td><%= post.problem %></td>
        <td><%= post.result %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'Anasayfa', :root %>



app/views/static_pages/sent.html.erb
<h1>Notebook Tedavi Merkezini Tercih ettiğiniz için teşekkürler.</h1>
<p>Arızanız bildirilmiştir. En kısa zamanda Notebook Tedavi Merkezine gelip cihazınızı gösteriniz.</p>
<%= link_to 'Anasayfaya dön', :root %>